### ISSUE TITLE
Error - Directive u'directRouter'

### ISSUE THREAD

**Issue by jmorcar** [cluther/ZenPacks.example.EventButton#2]
I have found a directive Error on Zenoss 5 (when Zenping process tries to start)
 
I have trace the error, here the ouput:
 
# serviced service logs zenping
 
W0721 13:41:25.005123 00001 controller.go:777] Health check running failed.
W0721 13:41:30.026936 00001 controller.go:777] Health check running failed.
I0721 13:41:31.835794 00001 controller.go:612] Starting service process.
I0721 13:41:31.836209 00001 instance.go:79] about to execute: /bin/sh , [-c exec su - zenoss -c "/opt/zenoss/bin/zenping run -c --duallog --monitor localhost "][2]
2015/07/21 13:41:35 200 4.867218ms POST /api/metrics/store
Traceback (most recent call last):
  File "/opt/zenoss/Products/ZenStatus/zenping.py", line 110, in <module>
    zcml.load_site()
  File "/opt/zenoss/lib/python2.7/site-packages/Zope2/App/zcml.py", line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/xmlconfig.py", line 649, in file
    include(context, name, package)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/opt/zenoss/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 109, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/opt/zenoss/lib/python2.7/site-packages/_xmlplus/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/opt/zenoss/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 216, in feed
    self._parser.Parse(data, isFinal)
  File "/opt/zenoss/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 364, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/xmlconfig.py", line 359, in endElementNS
    self.context.end()
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/config.py", line 558, in end
    self.stack.pop().finish()
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/config.py", line 706, in finish
    actions = self.handler(context, **args)
  File "/opt/zenoss/lib/python2.7/site-packages/OFS/metaconfigure.py", line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/xmlconfig.py", line 548, in include
    processxmlfile(f, context)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/xmlconfig.py", line 380, in processxmlfile
    parser.parse(src)
  File "/opt/zenoss/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 109, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/opt/zenoss/lib/python2.7/site-packages/_xmlplus/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/opt/zenoss/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 216, in feed
    self._parser.Parse(data, isFinal)
  File "/opt/zenoss/lib/python2.7/site-packages/_xmlplus/sax/expatreader.py", line 353, in start_element_ns
    AttributesNSImpl(newattrs, qnames))
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/xmlconfig.py", line 232, in startElementNS
    self.context.begin(name, data, info)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/config.py", line 555, in begin
    self.stack.append(self.stack[-1].contained(__name, __data, __info))
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/config.py", line 856, in contained
    return RootStackItem.contained(self, name, data, info)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/config.py", line 724, in contained
    factory = self.context.factory(self.context, name)
  File "/opt/zenoss/lib/python2.7/site-packages/zope/configuration/config.py", line 501, in factory
    raise ConfigurationError("Unknown directive", ns, n)
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/opt/zenoss/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/opt/zenoss/ZenPacks/ZenPacks.example.EventButton-1.0.0-py2.7.egg/ZenPacks/example/EventButton/configure.zcml", line 25.4
    ConfigurationError: ('Unknown directive', u'http://namespaces.zope.org/browser', u'directRouter')

**Comment by cluther** [comment]
It looks like my example was incomplete. Try adding the following line above the browser:directRouter directive in configure.zcml.

``` xml
<include package="Products.ZenUtils.extdirect.zope" file="meta.zcml"/>
```

I fixed the example accordingly in 69a3fc6.

**Comment by jmorcar** [comment]
Thanks for your reply! I will try this solution to test whether the zenping health is well again. After, my challenge it will be create a button than open a shell via SSH per Event, execute certains commands and export X11 to lauch interactive apps with the devices.

**Comment by jmorcar** [comment]
Perfect! I tested adding your fix and Zenping it's OK again.

**Comment by jmorcar** [comment]
Hello again, Sorry I'm trying to add new button features to your button development. I've created new function named getMyattribute on api.py file that obtain data from selected events. I don't know JavaScript language, but only I want create a dropdown button that shows the data return by my python def function getMyattribute but I don't known from what part of Javascript code can I call to my function.

Here is my eventclass2.js (modified with new dropdown button) : http://pastebin.com/c6nV7wUm 
Here is my api.py with my new getMyattribute function : http://pastebin.com/0BPEiFFH

Can you help me when you have a time? 

Thanks in advance
